# Generated by Django 3.2.8 on 2021-10-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tw', 'topWear'), ('bw', 'bottomWear'), ('m', 'Mobail'), ('l', 'laptop')], max_length=2),
        ),
    ]
